version: '3.8'

services:
  
  telegram-app:
    build: 
      context: ./app
      dockerfile: dockers/Dockerfile.telegram_app
    command: /bin/bash -c "python main.py tail -f /dev/null"
    volumes:
      - ./app/shared:/usr/src/home/shared
    depends_on:
      - server-db
    env_file:
      - ./.env
  
  server-db:
    build: 
      context: ./app/dockers/db
      dockerfile: Dockerfile
    expose:  
      - 5432
    env_file:
      - ./.env
