from tortoise import fields, models
from tortoise.contrib.pydantic import pydantic_model_creator

class Users(models.Model):
    # id primary key is autogenerated
    # user_id = fields.CharField(max_length=255)
    full_name = fields.CharField(max_length=255)
    company = fields.CharField(max_length=255)
    address = fields.CharField(max_length=255)
    timestamp = fields.DatetimeField(auto_new_add=True)

    def __str__(self):
        return self.user_id

class Orders(models.Model):
    # id primary key is autogenerated
    # user_id = fields.CharField(max_length=255)
    product = fields.CharField(max_length=255) # name of the product
    size  = fields.IntField() # qty of the order
    status = fields.CharField(max_length=255) # delivered/waiting
    transfer_time = fields.FloatField() # expected delivery time
    timestamp = fields.DatetimeField(auto_new_add=True) # order creation time

    def __str__(self):
        return self.user_id


Users_pydantic = pydantic_model_creator(Users)
Orders_pydantic = pydantic_model_creator(Orders)